// Generated by scripts/build-site.js. The publishable key is meant to be public.
export const CONFIG = {
  supabaseUrl: "https://ogogexuinuynaglkxeeh.supabase.co",
  supabaseKey: "sb_publishable_SjHkW_JyEnmsO-TACgJF0w_X1X3wLNA",
};
